### PR TITLE
Feat/infinite scroll

### LINKED ISSUE #60: [FEAT] NextJS infinite scroll pagination
**🔥 Is your feature request related to a problem? Please describe.**
Yeah! It takes quite a long time to load the page when a new user visits because onLoad we try to load every single user.

**Describe the solution you'd like**
The best way to tackle this lead time down is by adding Infinite scroll pagination to the web app.

It's quite weird when a web app takes so long to just load data. That's why I want a person who would integrate infinite scroll pagination. Pagination should be added to https://x.hellofaizan.me/api/explore API, as this api loads data in random order not just like a row.

### PR DESCRIPTION
**Pull request by rahulpandey70**
## What does this PR do?

This PR add infinite scrolling feature, some modification in code and some changes will appears because of different formatting.

Fixes #60 

## Type of change

- New feature (non-breaking change which adds functionality)

## How should this be tested?
x

In this infinite scrolling initial time fetched 9 users and after scrolling it will fetch 9 more users and it will goes till end.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hellofaizan** [comment]
It works but has few bugs. @rahulpandey70 

- On mobile view I am not able to smoothly scroll
- during on load, the skeleton UI loading is missing

Rest works great

**Comment by rahulpandey70** [comment]
> It works but has few bugs. @rahulpandey70
> 
> * On mobile view I am not able to smoothly scroll
> * during on load, the skeleton UI loading is missing
> 
> Rest works great

Thanks for your feedback, I'll fix it.

**Comment by rahulpandey70** [comment]
Hey @hellofaizan hope this time everything will work, will wait for your feedback.

**Comment by rahulpandey70** [comment]
Hey @hellofaizan hope this time everything will work, will wait for your feedback.

**Comment by hellofaizan** [comment]
@rahulpandey70 It works

Still on mobile view I am not able to smooth scroll. No idea why

**Comment by hellofaizan** [comment]
Try running preview on mobile view using
https://xprofile-git-fork-rahulpandey70-feat-infinit-83da71-hellofaizan.vercel.app/

**Comment by rahulpandey70** [comment]
> @rahulpandey70 It works
> 
> Still on mobile view I am not able to smooth scroll. No idea why

@hellofaizan Can you see? what is the issue, i'hv tried but i didn't find any solution. Although I am still looking for solution.

**Comment by hellofaizan** [comment]
I mobile browser we don't have access to console, so not able to find any issues, still I will look into it and figure it out

**Comment by hellofaizan** [comment]
Now it works. Crazy 🔥 @rahulpandey70

**Comment by hellofaizan** [comment]
About to merge.

Make sure to drop a ⭐ to the repository and if you want to discuss upcoming features - [Join Discord](https://discord.gg/vUHMxPvege)

**Comment by rahulpandey70** [comment]
> About to merge.
> 
> Make sure to drop a ⭐ to the repository and if you want to discuss upcoming features - [Join Discord](https://discord.gg/vUHMxPvege)

Sure

**Pull request merged**
