### PR TITLE
Profileadd

### PR DESCRIPTION
**Pull request by cdxgh**
## What does this PR do?

Fixes #(issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/hellofaizan/xprofile/blob/main/CONTRIBUTING.MD)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hellofaizan** [comment]
You doing it wrong

Just copy paste and edit this

,{
        "username": "hellofaizaan",
        "name": "Hello Faizan",
        "github": "hellofaizan",
        "banner_color": "#ff2500",
        "about": "I am a full stack developer and a competitive programmer. I love Chess♟️ also https://hellofaizan.me/"
    }

**Comment by cdxgh** [comment]
ok

**Review by cdxgh — COMMENTED** [review]
see this change

**Comment by hellofaizan** [comment]
Having a look

**Review by hellofaizan — COMMENTED** [review]
You are writing JSON in wrong formate. Copy whole data/users.jsom from GitHub and paste into your forked repo. Then add your data

**Comment by hellofaizan** [comment]
Clear all data from users.Json and replace that by

**Comment by hellofaizan** [comment]
[
  {
    "username": "Brandon4Tenn",
    "name": "Brandon Thomas",
    "github": "BThomas22tech",
    "banner_color": "#0085ca",
    "about": "Full-Stack Python Developer who loves to play the piano🎶 "
  },
  {
    "username": "hellofaizaan",
    "name": "Hello Faizan",
    "github": "hellofaizan",
    "banner_color": "#ff2500",
    "about": "Chess♟ Coding☕ Football⚽ Tech🧑‍💻 <> I do random stuff just to make other person laugh. Find me => https://hellofaizan.me/"
  },
  {
    "username": "zainab_nisa_",
    "name": "Zainab Nisa",
    "github": "ZainabNisa786",
    "banner_color": "#f5f5f5",
    "about": "I'm زينب | • learning Code • ui/ux-design"
  },
  {
    "username": "iaminfinil",
    "name": "Infinil",
    "github": "infinil",
    "banner_color": "#800080",
    "about": "Built Animenetic & SpaceVoid • Solo Developer 👨🏻‍💻 • Anime Otaku 📺 • Space Enthusiast 🚀 •  CSE Student 👨🏻‍🎓"
  },
  {
    "username": "nindri_mott",
    "name": "Ikhlaq Malik",
    "github": "ikhlaqmalik13",
    "banner_color": "#000080",
    "about": "1+1=10, 19: 48 | Koshur | Software Developer | CSE AMU | Lost in code, electronics, machines, graphs."
  },
  {
    "username": "Neutron975",
    "name": "Shiva",
    "github": "Shiva953",
    "banner_color": "#3b41ff",
    "about": "Paradoxically Naive Rational Optimist | Likes Technology,Open Source and Exploring Finance | Loves Podcasts, Books and Memes"
  },
  {
    "username": "bhavaygarg",
    "name": "Bhavay Garg",
    "github": "0takugod",
    "banner_color": "#48D1CC",
    "about": "CSE + Games + Anime + Open source = Me. | I love coffee. "
  },
  {
    "username": "farfa7886",
    "name": "Farfa",
    "github": "Farfa7886",
    "banner_color": "#09458f",
    "about": "15 y/o kid from Italy that has a passion for programming"
  },
  {
    "username": "Sxamoecode",
    "name": "Samuel",
    "github": "Sxamoecode",
    "banner_color": "#86098f",
    "about": "Software engineer | Backend development | Problem Solver | Loves contributing to Open Source && Collaborating"
  },
  {
    "username": "okkattiboy",
    "name": "Akshara Hegde",
    "github": "aksharahegde",
    "banner_color": "#00dbda",
    "about": "Senior Fullstack Engineer | Writer | Visit aksharahegde.xyz"
  },
  {
    "username": "BacotMath",
    "name": "Bang Domath",
    "github": "DomathID",
    "banner_color": "#008080",
    "about": "I I'am just an NPC | Anime Enthusiast | Write yukinoshita.web.id"
  },
  {
    "username": "dev_mannuu",
    "name": "Mannu",
    "github": "MannuVilasara",
    "banner_color": "#ff1493",
    "about": "Mannu | 16yo from India currenty working in cyber security | Chess, Anime, Coffee | Cats 🐈‍⬛ | Community Manager (Moderator at DEV communtiy)"
  },
  {
    "username": "prabhurupe",
    "name": "Rupesh Prabhu",
    "github": "rupeshprabhu",
    "banner_color": "#00dbda",
    "about": "Rupesh Prabhu | Frontend Developer currently in India | Loves to review and understand technology"
  },
  {
    "username": "GurnavChaudhary",
    "name": "Gurnav chaudhary",
    "github": "Gurnav224",
    "banner_color": "#00dbda",
    "about": "I'm an aspiring full-stack MERN developer from India, currently in my final year of BCA studies"
  },
  {
    "username": "salman_codes",
    "name": "Salman Akhtar",
    "github": "salmanakhtar57",
    "banner_color": "#00dbda",
    "about": "Web Developer | Machine Learning Enthusiast | Tech Writer"
  },
  {
    "username": "AsharMallick86",
    "name": "Ashar Mallick",
    "github": "AsharMallick",
    "banner_color": "#d4d319",
    "about": "I'm an aspiring full-stack MERN developer from Pakistan who converts coffee into code"
  },
  {
    "username": "abdulqu87130365",
    "name": "Abdul Quadir",
    "github": "cdxgh",
    "banner_color": "#ff2501",
    "about": " Coding☕ cricket Tech🧑‍💻. Innovative Developer & Entrepreneur shaping impactful tech solutions for a better future. > https: //abdulquadir-portfolio-website.netlify.app/"
  }

]

**Comment by hellofaizan** [comment]
Why you delete it?

**Comment by hellofaizan** [comment]
> [
>   {
>     "username": "Brandon4Tenn",
>     "name": "Brandon Thomas",
>     "github": "BThomas22tech",
>     "banner_color": "#0085ca",
>     "about": "Full-Stack Python Developer who loves to play the piano🎶 "
>   },
>   {
>     "username": "hellofaizaan",
>     "name": "Hello Faizan",
>     "github": "hellofaizan",
>     "banner_color": "#ff2500",
>     "about": "Chess♟ Coding☕ Football⚽ Tech🧑‍💻 <> I do random stuff just to make other person laugh. Find me => https://hellofaizan.me/"
>   },
>   {
>     "username": "zainab_nisa_",
>     "name": "Zainab Nisa",
>     "github": "ZainabNisa786",
>     "banner_color": "#f5f5f5",
>     "about": "I'm زينب | • learning Code • ui/ux-design"
>   },
>   {
>     "username": "iaminfinil",
>     "name": "Infinil",
>     "github": "infinil",
>     "banner_color": "#800080",
>     "about": "Built Animenetic & SpaceVoid • Solo Developer 👨🏻‍💻 • Anime Otaku 📺 • Space Enthusiast 🚀 •  CSE Student 👨🏻‍🎓"
>   },
>   {
>     "username": "nindri_mott",
>     "name": "Ikhlaq Malik",
>     "github": "ikhlaqmalik13",
>     "banner_color": "#000080",
>     "about": "1+1=10, 19: 48 | Koshur | Software Developer | CSE AMU | Lost in code, electronics, machines, graphs."
>   },
>   {
>     "username": "Neutron975",
>     "name": "Shiva",
>     "github": "Shiva953",
>     "banner_color": "#3b41ff",
>     "about": "Paradoxically Naive Rational Optimist | Likes Technology,Open Source and Exploring Finance | Loves Podcasts, Books and Memes"
>   },
>   {
>     "username": "bhavaygarg",
>     "name": "Bhavay Garg",
>     "github": "0takugod",
>     "banner_color": "#48D1CC",
>     "about": "CSE + Games + Anime + Open source = Me. | I love coffee. "
>   },
>   {
>     "username": "farfa7886",
>     "name": "Farfa",
>     "github": "Farfa7886",
>     "banner_color": "#09458f",
>     "about": "15 y/o kid from Italy that has a passion for programming"
>   },
>   {
>     "username": "Sxamoecode",
>     "name": "Samuel",
>     "github": "Sxamoecode",
>     "banner_color": "#86098f",
>     "about": "Software engineer | Backend development | Problem Solver | Loves contributing to Open Source && Collaborating"
>   },
>   {
>     "username": "okkattiboy",
>     "name": "Akshara Hegde",
>     "github": "aksharahegde",
>     "banner_color": "#00dbda",
>     "about": "Senior Fullstack Engineer | Writer | Visit aksharahegde.xyz"
>   },
>   {
>     "username": "BacotMath",
>     "name": "Bang Domath",
>     "github": "DomathID",
>     "banner_color": "#008080",
>     "about": "I I'am just an NPC | Anime Enthusiast | Write yukinoshita.web.id"
>   },
>   {
>     "username": "dev_mannuu",
>     "name": "Mannu",
>     "github": "MannuVilasara",
>     "banner_color": "#ff1493",
>     "about": "Mannu | 16yo from India currenty working in cyber security | Chess, Anime, Coffee | Cats 🐈‍⬛ | Community Manager (Moderator at DEV communtiy)"
>   },
>   {
>     "username": "prabhurupe",
>     "name": "Rupesh Prabhu",
>     "github": "rupeshprabhu",
>     "banner_color": "#00dbda",
>     "about": "Rupesh Prabhu | Frontend Developer currently in India | Loves to review and understand technology"
>   },
>   {
>     "username": "GurnavChaudhary",
>     "name": "Gurnav chaudhary",
>     "github": "Gurnav224",
>     "banner_color": "#00dbda",
>     "about": "I'm an aspiring full-stack MERN developer from India, currently in my final year of BCA studies"
>   },
>   {
>     "username": "salman_codes",
>     "name": "Salman Akhtar",
>     "github": "salmanakhtar57",
>     "banner_color": "#00dbda",
>     "about": "Web Developer | Machine Learning Enthusiast | Tech Writer"
>   },
>   {
>     "username": "AsharMallick86",
>     "name": "Ashar Mallick",
>     "github": "AsharMallick",
>     "banner_color": "#d4d319",
>     "about": "I'm an aspiring full-stack MERN developer from Pakistan who converts coffee into code"
>   },
>   {
>     "username": "abdulqu87130365",
>     "name": "Abdul Quadir",
>     "github": "cdxgh",
>     "banner_color": "#ff2501",
>     "about": " Coding☕ cricket Tech🧑‍💻. Innovative Developer & Entrepreneur shaping impactful tech solutions for a better future. > https: //abdulquadir-portfolio-website.netlify.app/"
>   }
> 
> ]

Create `users.json` again and paste this above data into it

**Pull request closed without merging**
