### PR TITLE
Fixed The Index in the Map Function

### PR DESCRIPTION
**Pull request by ArnabBCA**
## What does this PR do?
While running locally there is a Console error in key field.
In this modified code, I replaced (index) with (_, index) in the map function, which ensures that each element has a unique key based on its index.

## Type of change
Before
Error
After
Fixed

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by hellofaizan** [comment]
Awesome 🔥

**Comment by ArnabBCA** [comment]
Do you also want to remove the unwanted lines from the console?

**Comment by hellofaizan** [comment]
Yeah. If you can do that. Why not

**Comment by ArnabBCA** [comment]
ok give me a moment ;)

**Comment by hellofaizan** [comment]
I was thinking about adding tags to it. If you can help with that @ArnabBCA

**Pull request merged**
