### PR TITLE
Changed Hero Image

### PR DESCRIPTION
**Pull request by CodeWizarz**
## What does this PR do?

Changed Hero Image to the latest and using Image inside the public dir to display instead of using a url to show image

### CODE REVIEW

**Comment by hellofaizan** [comment]
This mention is good, better was just pasting the screenshot to Readme file while editing

**Comment by hellofaizan** [comment]
Either pasting or just drag and drop

**Comment by hellofaizan** [comment]
**How you should do it**

- Remove that hero image from public folder
- Edit readme file and remove that image tag
- Either drag and drop the screenshot to this readme file or copy that image from folder and paste on that line

- You can also add your profile by adding your data in `data/users.json`

That's it. I don't have access to my machine, so I am unable to do it on my own

**Comment by hellofaizan** [comment]
Hey @CodeWizarz you there?

**Comment by CodeWizarz** [comment]
> Hey @CodeWizarz you there?

Hey I'm currently down due to power outage.
I guess this is fine you can just update to latest hero image just by adding a new image to public. This Is how I have Linked the gif's and png's in other major projects. This doesn't conflict with anything with the src so it should be fine.

**Comment by hellofaizan** [comment]
I know it will not conflict, it's just it will become hectic every other time we have to change hero image in near future

**Comment by hellofaizan** [comment]
Okay let it be. I will merge it. Do add your profile when power is restored

**Comment by hellofaizan** [comment]
I am doing those things. Check out the Dev branch of this repository

**Comment by hellofaizan** [comment]
I will be adding a personal portfolio section and some pinned GitHub repos

**Comment by hellofaizan** [comment]
Join discord where we can discuss all upcoming features
https://discord.gg/vUHMxPvege

**Pull request merged**
