### PR TITLE
Update users.json

### PR DESCRIPTION
**Pull request by Farfa7886**

### CODE REVIEW

**Comment by Farfa7886** [comment]
Added my profile

**Comment by Farfa7886** [comment]
Added my profile

**Comment by hellofaizan** [comment]
It cooks ok. But brother you have written too low 'about' field. It will break the UI of the card. If you don't mind, can you add a little bit of text to the 'about' field. Like maximum 3 goes

**Comment by hellofaizan** [comment]
Check the preview. https://xprofile-git-fork-farfa7886-main-hellofaizan.vercel.app/

**Comment by hellofaizan** [comment]
Cool 😎

⭐ The repo also

**Pull request merged**
