### PR TITLE
Fix #54 Added feature Theme toggle

### LINKED ISSUE #54: [FEAT] Add theme toogle
As a user, If you want to be able to switch between light and dark themes on the website/app, so that you can choose the one that is easier on my eyes or fits your preferences.

To implement this feature, we will need to add a button or switch somewhere on the page that the user can click or tap to toggle the theme. When the user switches the theme, we will need to update the CSS styles accordingly to apply the appropriate colors, fonts, and other design elements.

In addition, we should consider storing the user's preference for the theme in a cookie or local storage, so that it persists across page reloads and sessions.

By adding this functionality, we can improve the user experience and make the website/app more accessible and customizable for our users.

### PR DESCRIPTION
**Pull request by AsharMallick**
Added feature of toggle theme #54

### CODE REVIEW

**Comment by hellofaizan** [comment]
**Error**

**Comment by hellofaizan** [comment]
Looking good

**Comment by hellofaizan** [comment]
Few issues

- Fix the image stroke when I'm in light mode


- Fix the buttons background also in light mode
- Fix the logo in light mode
- Theme toogle save preferences are missing
`Default theme should be dark. When I'm in light mode, preferences should be saved and when I visit the website again, it should be that same theme`
- Toogle button is missing in small screens

**Comment by hellofaizan** [comment]
Issues
https://xprofile-git-fork-asharmallick-feature-theme-toggle-hellofaizan.vercel.app/

Checkout

**Comment by hellofaizan** [comment]
Error is Theme type is required in home page

**Comment by hellofaizan** [comment]
Error from console is
**Theme type is required in index.js**

**Comment by hellofaizan** [comment]
Deployed successfully. Let me have a look and preview the code base

**Comment by AsharMallick** [comment]
Yes Sure!

**Comment by hellofaizan** [comment]
If you don't mind can you do these also


- Reduce the gap between divs in small screen devices
- Reduce X axis padding theme toggle buttons.

That's it. I will merge it. Also can you add your profile in here. Drop a ⭐

**Comment by hellofaizan** [comment]
Good to merge

**Comment by AsharMallick** [comment]
Yes check it

**Comment by hellofaizan** [comment]
GGs merging your pr. Thanks for the contribution. If you're on Discord, join now to discuss about future features and other Open Source Projects with us https://discord.gg/vUHMxPvege

**Pull request merged**
