### PR TITLE
Added my X profile :)

### PR DESCRIPTION
**Pull request by khushi2762**
Updated my data of X profile!

### CODE REVIEW

**Comment by hellofaizan** [comment]
Everything was alright. Why you closed the PR @khushi2762

**Comment by khushi2762** [comment]
Hey Faizan. I closed the pr because it had some conflicts. But now I have made the pr again.🤖🤙

**Comment by hellofaizan** [comment]
@khushi2762 Oo. I merged the new pr

**Comment by hellofaizan** [comment]
Make sure to mark a ⭐ star to repository and [Join Discord](https://discord.gg/vUHMxPvege)

**Pull request closed without merging**
