### PR TITLE
Update users.json -> Shiva

### PR DESCRIPTION
**Pull request by Shiva953**

### CODE REVIEW

**Comment by hellofaizan** [comment]
Looks good. No conflicts.

**Comment by hellofaizan** [comment]
@Shiva953 you have to reduce amount of text in `about` field. As it will break the UI of card. It was mentioned to write less in about field. Try reducing it lil bit

**Review by hellofaizan — CHANGES_REQUESTED** [review]
Try reducing about text and make it as max as the above data in users.json

**Comment by Shiva953** [comment]
> Try reducing about text and make it as max as the above data in users.json

Sure, let me reduce it

**Pull request merged**
